name: kadosh_website
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.1.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/first_friday_poster/december.png
    - assets/kadosh-logo.png
    - assets/kadosh-title.png
    - assets/team.jpg
    - assets/community.png
    - assets/orange-sky.jpg
    - assets/sandra_profile.jpg
    - assets/aires_profile.jpg
    - assets/shando_profile.jpg
    - assets/savio_profile.jpg
    - assets/leon_profile.jpg
    - assets/aires_sandra.jpg

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
